export const COUNTRIES = [
  "China",
  "United States",
  "Germany",
  "Japan",
  "South Korea",
  "Taiwan",
  "Vietnam",
  "Thailand",
  "Malaysia",
  "Indonesia",
  "Singapore",
  "Australia",
  "United Kingdom",
  "United Arab Emirates",
  "Saudi Arabia",
  "Bangladesh",
  "Sri Lanka",
  "Nepal",
  "New Zealand",
  "Italy",
  "France",
  "Netherlands",
  "Turkey",
  "Brazil",
  "Canada",
  "Mexico",
  "South Africa",
  "Nigeria",
  "Russia",
  "Switzerland",
] as const;
